apiVersion: v1
kind: Service
metadata:
  name: container-provisioner
  namespace: backend
spec:
  selector:
    app: container-provisioner
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP
