apiVersion: v1
kind: ServiceAccount
metadata:
  name: container-provisioner
  namespace: backend
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::986129558966:role/smctf-dev-irsa-container-provisioner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: container-provisioner-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "create", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["list", "get", "create", "delete"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "get"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: container-provisioner-binding
subjects:
  - kind: ServiceAccount
    name: container-provisioner
    namespace: backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: container-provisioner-role
