apiVersion: v1
kind: Secret
metadata:
  name: smctf-backend-secret
  namespace: backend
type: Opaque
stringData:
  DB_PASSWORD: "app_password"
  REDIS_PASSWORD: ""
  JWT_SECRET: "change-me"
  FLAG_HMAC_SECRET: "change-me-too"
  STACKS_PROVISIONER_API_KEY: "change-me"
  LOG_DISCORD_WEBHOOK_URL: ""
  LOG_SLACK_WEBHOOK_URL: ""
  S3_ACCESS_KEY_ID: ""
  S3_SECRET_ACCESS_KEY: ""
