{{- if .Values.namespaces.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.backend }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.stacks }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.logging }}
---
{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.monitoring }}
{{- end }}
{{- end }}
