{{- if .Values.stacksDenyNetworkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-egress-for-labeled-pods-in-stacks
  namespace: {{ .Values.namespaces.stacks }}
spec:
  podSelector:
    matchLabels:
      block-egress: "true"
  policyTypes:
    - Egress
  egress: []
---
{{- end }}
{{- if and .Values.stacksDenyNetworkPolicy.enabled .Values.stacksDenyNetworkPolicy.namespaces }}
{{- range $ns := .Values.stacksDenyNetworkPolicy.namespaces }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $.Values.stacksDenyNetworkPolicy.namePrefix }}-{{ $ns }}
  namespace: {{ $ns }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: NotIn
                values:
                  - {{ $.Values.stacksDenyNetworkPolicy.denyFromNamespace }}
{{- end }}
{{- end }}
