{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.secretName }}
  namespace: {{ .Values.namespaces.backend }}
type: Opaque
stringData:
{{ toYaml .Values.backend.secret | indent 2 }}
---
{{- end }}
{{- if .Values.provisioner.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.provisioner.secretName }}
  namespace: {{ .Values.namespaces.backend }}
type: Opaque
stringData:
{{ toYaml .Values.provisioner.secret | indent 2 }}
{{- end }}
