{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.configName }}
  namespace: {{ .Values.namespaces.backend }}
data:
{{ toYaml .Values.backend.config | indent 2 }}
---
{{- end }}
{{- if .Values.provisioner.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.provisioner.configName }}
  namespace: {{ .Values.namespaces.backend }}
data:
{{ toYaml .Values.provisioner.config | indent 2 }}
{{- end }}
