{{- if .Values.fluentbit.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fluentbit.configMapName }}
  namespace: {{ .Values.fluentbit.namespace | default .Values.namespaces.logging }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Daemon        Off
        Log_Level     info
        Parsers_File  parsers.conf

    [INPUT]
        Name          tail
        Path          /var/log/containers/*.log
        Tag           kube.*
        Parser        cri
        Mem_Buf_Limit 10MB
        Skip_Long_Lines On
        DB            /var/log/fluent-bit/fluent-bit-pos.db

    [FILTER]
        Name          kubernetes
        Match         kube.*
        Kube_URL      https://kubernetes.default.svc:443
        Kube_Tag_Prefix kube.var.log.containers.
        Merge_Log     On
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [FILTER]
        Name          grep
        Match         kube.*
        Regex         kubernetes['namespace_name'] ^backend$

    [OUTPUT]
        Name              cloudwatch_logs
        Match             kube.*
        region            ${AWS_REGION}
        log_group_name    ${LOG_GROUP_NAME}
        log_stream_prefix ${LOG_STREAM_PREFIX}
        auto_create_group true
  parsers.conf: |
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>P|F) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
{{- end }}
