{{- if .Values.provisioner.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.provisioner.rbac.clusterRoleName }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "create", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["list", "get", "create", "delete"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "get"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.provisioner.rbac.clusterRoleBindingName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.provisioner.serviceAccount.name }}
    namespace: {{ .Values.provisioner.serviceAccount.namespace | default .Values.namespaces.backend }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.provisioner.rbac.clusterRoleName }}
{{- end }}
